services:
  # Web service configuration
  - type: web
    name: streamhub
    runtime: python3
    plan: starter  # Change to 'standard' or 'pro' for production
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        fromService:
          type: web
          name: streamhub
          property: port
    healthCheckPath: /health
    disk:
      name: streamhub-disk
      mountPath: /app/static
      sizeGB: 1

  # PostgreSQL database
  - type: pserv
    name: streamhub-db
    runtime: postgresql
    plan: starter  # Change to 'standard' for production
    databaseName: streamhub
    databaseUser: streamhub_user
    region: oregon  # Change to your preferred region

# Environment variables (secrets should be set in Render dashboard)
envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: streamhub-db
      property: connectionString
